language: en
pipeline:
- name: SpacyNLP
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: SklearnIntentClassifier
- name: ResponseSelector
policies:
- name: EmbeddingPolicy
  state_featurizer:
  - name: LabelTokenizerSingleStateFeaturizer
  batch_strategy: balanced
  epochs: 200
  attn_shift_range: 5
  max_history: 6
- name: MappingPolicy